using System.Globalization;

namespace ChuliTirth.Helpers;

// Static translations for hardcoded UI chrome (nav, buttons, footer labels) that isn't DB-driven.
// DB content (rooms, facilities, quotes, etc.) is localized via LocalizationHelper instead.
public static class UiText
{
    private static readonly Dictionary<string, (string En, string Gu, string Hi)> Map = new()
    {
        ["Home"] = ("Home", "હોમ", "होम"),
        ["About"] = ("About", "અમારા વિશે", "हमारे बारे में"),
        ["Rooms"] = ("Rooms", "રૂમ", "कमरे"),
        ["Facilities"] = ("Facilities", "સુવિધાઓ", "सुविधाएं"),
        ["Bhojanshala"] = ("Bhojanshala", "ભોજનશાળા", "भोजनशाला"),
        ["JainTithi"] = ("Jain Tithi", "જૈન તિથિ", "जैन तिथि"),
        ["Gallery"] = ("Gallery", "ગેલેરી", "गैलरी"),
        ["BookingRules"] = ("Booking Rules", "બુકિંગ નિયમો", "बुकिंग नियम"),
        ["Contact"] = ("Contact", "સંપર્ક", "संपर्क"),
        ["MyBookings"] = ("My Bookings", "મારા બુકિંગ", "मेरी बुकिंग"),
        ["Login"] = ("Login", "લોગિન", "लॉगिन"),
        ["Logout"] = ("Logout", "લોગઆઉટ", "लॉगआउट"),
        ["Admin"] = ("Admin", "એડમિન", "एडमिन"),
        ["BookNow"] = ("Book Now", "હવે બુક કરો", "अभी बुक करें"),
        ["QuickLinks"] = ("Quick Links", "ઝડપી લિંક્સ", "त्वरित लिंक"),
        ["RoomBooking"] = ("Room Booking", "રૂમ બુકિંગ", "कमरा बुकिंग"),
        ["Policies"] = ("Policies", "નીતિઓ", "नीतियां"),
        ["PrivacyPolicy"] = ("Privacy Policy", "ગોપનીયતા નીતિ", "गोपनीयता नीति"),
        ["HowToReach"] = ("How to Reach", "કેવી રીતે પહોંચવું", "कैसे पहुंचें"),
        ["ContactHeading"] = ("Contact", "સંપર્ક", "संपर्क"),
        ["ViewOnMaps"] = ("View on Google Maps", "ગૂગલ મેપ્સ પર જુઓ", "गूगल मैप्स पर देखें"),
        ["CheckIn"] = ("Check-in", "ચેક-ઇન", "चेक-इन"),
        ["CheckOut"] = ("Check-out", "ચેક-આઉટ", "चेक-आउट"),
        ["Guests"] = ("Number of Guests", "મહેમાનોની સંખ્યા", "मेहमानों की संख्या"),
        ["RoomsCount"] = ("Number of Rooms", "રૂમની સંખ્યા", "कमरों की संख्या"),
        ["CheckAvailability"] = ("Check Availability", "ઉપલબ્ધતા તપાસો", "उपलब्धता जांचें"),
        ["ViewRooms"] = ("View Rooms", "રૂમ જુઓ", "कमरे देखें"),
        ["BookYourStay"] = ("Book Your Stay", "તમારો રોકાણ બુક કરો", "अपना प्रवास बुक करें"),
        ["ViewFullGallery"] = ("View Full Gallery", "સંપૂર્ણ ગેલેરી જુઓ", "पूरी गैलरी देखें"),
        ["ContactUs"] = ("Contact Us", "અમારો સંપર્ક કરો", "हमसे संपर्क करें"),
        ["AllRightsReserved"] = ("All rights reserved.", "બધા હકો સુરક્ષિત છે.", "सर्वाधिकार सुरक्षित।"),

        ["AccommodationEyebrow"] = ("Accommodation", "આવાસ", "आवास"),
        ["OurRooms"] = ("Our Rooms", "અમારા રૂમ", "हमारे कमरे"),
        ["Amenities"] = ("Amenities", "સુવિધાઓ", "सुविधाएं"),
        ["OccupancyAndBeds"] = ("Occupancy & Beds", "ક્ષમતા અને પથારી", "क्षमता और बिस्तर"),
        ["AttachedBathroom"] = ("Attached bathroom", "જોડાયેલ બાથરૂમ", "संलग्न बाथरूम"),
        ["SharedBathroom"] = ("Shared bathroom", "સહિયારું બાથરૂમ", "साझा बाथरूम"),
        ["AvailabilityNext30"] = ("Availability — Next 30 Days", "ઉપલબ્ધતા — આગામી 30 દિવસ", "उपलब्धता — अगले 30 दिन"),
        ["Available"] = ("Available", "ઉપલબ્ધ", "उपलब्ध"),
        ["PartiallyBooked"] = ("Partially booked", "આંશિક રીતે બુક થયેલ", "आंशिक रूप से बुक"),
        ["FullyBooked"] = ("Fully booked", "સંપૂર્ણ બુક થયેલ", "पूरी तरह बुक"),
        ["BookThisRoom"] = ("Book This Room", "આ રૂમ બુક કરો", "यह कमरा बुक करें"),
        ["JainBhojanshala"] = ("Jain Bhojanshala", "જૈન ભોજનશાળા", "जैन भोजनशाला"),
        ["BhojanshalaSubtitle"] = ("Pure Jain vegetarian meals served daily.", "દરરોજ શુદ્ધ જૈન શાકાહારી ભોજન પીરસવામાં આવે છે.", "प्रतिदिन शुद्ध जैन शाकाहारी भोजन परोसा जाता है।"),
        ["Meal"] = ("Meal", "ભોજન", "भोजन"),
        ["Timing"] = ("Timing", "સમય", "समय"),
        ["Note"] = ("Note", "નોંધ", "टिप्पणी"),
        ["BookingRulesAndPolicies"] = ("Booking Rules & Policies", "બુકિંગ નિયમો અને નીતિઓ", "बुकिंग नियम और नीतियां"),
        ["Adults"] = ("Adults", "પુખ્ત", "वयस्क"),
        ["SelectRoom"] = ("Select Room", "રૂમ પસંદ કરો", "कमरा चुनें"),
        ["TrackYourBooking"] = ("Track Your Booking", "તમારું બુકિંગ ટ્રૅક કરો", "अपनी बुकिंग ट्रैक करें"),
        ["Track"] = ("Track", "ટ્રૅક કરો", "ट्रैक करें"),
        ["BookingNumber"] = ("Booking Number", "બુકિંગ નંબર", "बुकिंग नंबर"),
        ["Status"] = ("Status", "સ્થિતિ", "स्थिति"),
        ["Total"] = ("Total", "કુલ", "कुल"),
        ["JainTithiCalendar"] = ("Jain Tithi Calendar", "જૈન તિથિ કૅલેન્ડર", "जैन तिथि कैलेंडर"),
        ["Date"] = ("Date", "તારીખ", "तारीख"),
        ["Paksha"] = ("Paksha", "પક્ષ", "पक्ष"),
        ["Tithi"] = ("Tithi", "તિથિ", "तिथि"),
        ["SpecialOccasion"] = ("Special Occasion", "ખાસ પ્રસંગ", "विशेष अवसर"),
        ["Today"] = ("Today", "આજે", "आज"),
        ["Room"] = ("Room", "રૂમ", "कमरा"),
        ["Dates"] = ("Dates", "તારીખો", "तारीखें"),
        ["Payment"] = ("Payment", "ચુકવણી", "भुगतान"),
        ["Cancel"] = ("Cancel", "રદ કરો", "रद्द करें"),
        ["AvailableRooms"] = ("Available Rooms", "ઉપલબ્ધ રૂમ", "उपलब्ध कमरे"),
        ["GuestsShort"] = ("Guests", "મહેમાનો", "मेहमान"),
        ["GuestInformation"] = ("Guest Information", "મહેમાન માહિતી", "अतिथि जानकारी"),
        ["ContinueToSummary"] = ("Continue to Booking Summary", "બુકિંગ સારાંશ પર આગળ વધો", "बुकिंग सारांश पर जारी रखें"),
        ["BookingSummary"] = ("Booking Summary", "બુકિંગ સારાંશ", "बुकिंग सारांश"),
        ["RoomType"] = ("Room Type", "રૂમનો પ્રકાર", "कमरे का प्रकार"),
        ["NumberOfNights"] = ("Number of Nights", "રાતની સંખ્યા", "रातों की संख्या"),
        ["GuestName"] = ("Guest Name", "મહેમાનનું નામ", "अतिथि का नाम"),
        ["Contact"] = ("Contact", "સંપર્ક", "संपर्क"),
        ["RoomAmount"] = ("Room Amount", "રૂમની રકમ", "कमरे की राशि"),
        ["AdditionalCharges"] = ("Additional Charges", "વધારાના શુલ્ક", "अतिरिक्त शुल्क"),
        ["TotalAmount"] = ("Total Amount", "કુલ રકમ", "कुल राशि"),
        ["ConfirmBooking"] = ("Confirm Booking", "બુકિંગ કન્ફર્મ કરો", "बुकिंग की पुष्टि करें"),
        ["BookingConfirmed"] = ("Booking Confirmed", "બુકિંગ કન્ફર્મ થયું", "बुकिंग की पुष्टि हो गई"),
        ["PrintBooking"] = ("Print Booking", "બુકિંગ પ્રિન્ટ કરો", "बुकिंग प्रिंट करें"),
        ["EmailConfirmation"] = ("Email Confirmation", "ઇમેઇલ પુષ્ટિ", "ईमेल पुष्टि"),
        ["ViewMyBookings"] = ("View My Bookings", "મારા બુકિંગ જુઓ", "मेरी बुकिंग देखें"),
        ["CompletePayment"] = ("Complete Payment", "ચુકવણી પૂર્ણ કરો", "भुगतान पूरा करें"),
        ["AmountDue"] = ("Amount Due", "બાકી રકમ", "देय राशि"),
        ["RoomsHeader"] = ("Room(s)", "રૂમ(ઓ)", "कमरा/कमरे"),
        ["SendMessage"] = ("Send Message", "સંદેશ મોકલો", "संदेश भेजें"),
        ["CreateAccount"] = ("Create Account", "ખાતું બનાવો", "खाता बनाएं"),
        ["Register"] = ("Register", "નોંધણી કરો", "पंजीकरण करें"),
        ["AlreadyHaveAccount"] = ("Already have an account?", "પહેલેથી જ ખાતું છે?", "पहले से खाता है?"),
        ["AccessDenied"] = ("Access Denied", "પ્રવેશ નામંજૂર", "पहुंच अस्वीकृत"),
        ["NoPermission"] = ("You do not have permission to view this page.", "આ પૃષ્ઠ જોવાની તમને પરવાનગી નથી.", "आपको यह पेज देखने की अनुमति नहीं है।"),
        ["GoHome"] = ("Go Home", "હોમ પર જાઓ", "होम पर जाएं"),

        // Home page
        ["HomeHeroLead"] = ("A serene Jain Dharamshala offering comfortable accommodation, pure vegetarian Bhojanshala and a peaceful spiritual atmosphere for every pilgrim.", "દરેક યાત્રાળુ માટે આરામદાયક આવાસ, શુદ્ધ શાકાહારી ભોજનશાળા અને શાંત આધ્યાત્મિક વાતાવરણ પ્રદાન કરતી શાંત જૈન ધર્મશાળા.", "हर यात्री के लिए आरामदायक आवास, शुद्ध शाकाहारी भोजनशाला और शांत आध्यात्मिक वातावरण प्रदान करने वाली शांत जैन धर्मशाला।"),
        ["AboutTheTirth"] = ("About the Tirth", "તીર્થ વિશે", "तीर्थ के बारे में"),
        ["SacredPlaceHeading"] = ("A Sacred Place of Jain Devotion", "જૈન ભક્તિનું પવિત્ર સ્થળ", "जैन भक्ति का पवित्र स्थान"),
        ["HomeAboutSample"] = ("Sample content — replace with verified details via Admin > About. Chuli Tirth welcomes pilgrims from across the country for darshan, puja and peaceful stays.", "નમૂના સામગ્રી — એડમિન > અમારા વિશે દ્વારા ચકાસાયેલ વિગતો સાથે બદલો. ચુલી તીર્થ દેશભરના યાત્રાળુઓનું દર્શન, પૂજા અને શાંત રોકાણ માટે સ્વાગત કરે છે.", "नमूना सामग्री — एडमिन > हमारे बारे में के माध्यम से सत्यापित विवरण से बदलें। चुली तीर्थ देशभर के यात्रियों का दर्शन, पूजा और शांत प्रवास के लिए स्वागत करता है।"),
        ["RoomCategories"] = ("Room Categories", "રૂમના પ્રકારો", "कमरों के प्रकार"),
        ["WhyStayWithUs"] = ("Why Stay With Us", "અમારી સાથે શા માટે રોકાવું", "हमारे साथ क्यों ठहरें"),
        ["JainValuesHeading"] = ("Jain Values, Hospitality & Comfort", "જૈન મૂલ્યો, આતિથ્ય અને આરામ", "जैन मूल्य, आतिथ्य और आराम"),
        ["SafePeaceful"] = ("Safe & Peaceful", "સુરક્ષિત અને શાંત", "सुरक्षित और शांत"),
        ["SafePeacefulDesc"] = ("CCTV-monitored premises with a calm, respectful environment.", "સીસીટીવી-નિરીક્ષિત પરિસર, શાંત અને આદરપૂર્ણ વાતાવરણ સાથે.", "सीसीटीवी-निगरानी वाला परिसर, शांत और सम्मानजनक वातावरण के साथ।"),
        ["PureJainBhojan"] = ("Pure Jain Bhojan", "શુદ્ધ જૈન ભોજન", "शुद्ध जैन भोजन"),
        ["PureJainBhojanDesc"] = ("Strictly Jain vegetarian food served in our Bhojanshala.", "અમારી ભોજનશાળામાં સંપૂર્ણપણે જૈન શાકાહારી ભોજન પીરસવામાં આવે છે.", "हमारी भोजनशाला में पूर्णतः जैन शाकाहारी भोजन परोसा जाता है।"),
        ["FamilyFriendly"] = ("Family Friendly", "પરિવાર માટે અનુકૂળ", "परिवार के लिए अनुकूल"),
        ["FamilyFriendlyDesc"] = ("Spacious rooms and easy access for elderly visitors.", "વિશાળ રૂમ અને વૃદ્ધ મુલાકાતીઓ માટે સરળ પ્રવેશ.", "विशाल कमरे और बुज़ुर्ग अतिथियों के लिए सुगम पहुंच।"),
        ["SpiritualAtmosphere"] = ("Spiritual Atmosphere", "આધ્યાત્મિક વાતાવરણ", "आध्यात्मिक वातावरण"),
        ["SpiritualAtmosphereDesc"] = ("Close to temple and prayer areas for daily darshan.", "દૈનિક દર્શન માટે મંદિર અને પ્રાર્થના સ્થળની નજીક.", "दैनिक दर्शन के लिए मंदिर और प्रार्थना स्थल के निकट।"),
        ["Glimpses"] = ("Glimpses", "ઝલક", "झलक"),
        ["GetInTouch"] = ("Get in Touch", "સંપર્કમાં રહો", "संपर्क में रहें"),
        ["ContactAndLocation"] = ("Contact & Location", "સંપર્ક અને સ્થળ", "संपर्क और स्थान"),

        // About page
        ["DharamshalaManagement"] = ("Dharamshala & Management", "ધર્મશાળા અને સંચાલન", "धर्मशाला और प्रबंधन"),
        ["DharamshalaManagementSample"] = ("Sample content — the Dharamshala is managed by the local Jain Trust to serve pilgrims with clean accommodation and Bhojanshala facilities.", "નમૂના સામગ્રી — ધર્મશાળાનું સંચાલન સ્થાનિક જૈન ટ્રસ્ટ દ્વારા યાત્રાળુઓને સ્વચ્છ આવાસ અને ભોજનશાળા સુવિધાઓ પૂરી પાડવા માટે કરવામાં આવે છે.", "नमूना सामग्री — धर्मशाला का संचालन स्थानीय जैन ट्रस्ट द्वारा यात्रियों को स्वच्छ आवास और भोजनशाला सुविधाएं प्रदान करने के लिए किया जाता है।"),
        ["OurMission"] = ("Our Mission", "અમારું ધ્યેય", "हमारा उद्देश्य"),
        ["OurMissionSample"] = ("Sample content — to serve every pilgrim with Sadharmik Bhakti (devotion to fellow Jains) in a peaceful, spiritual environment.", "નમૂના સામગ્રી — શાંત, આધ્યાત્મિક વાતાવરણમાં સાધર્મિક ભક્તિ (સહધર્મી જૈનો પ્રત્યે ભક્તિ) સાથે દરેક યાત્રાળુની સેવા કરવી.", "नमूना सामग्री — शांत, आध्यात्मिक वातावरण में साधर्मिक भक्ति (सहधर्मी जैनों के प्रति भक्ति) के साथ हर यात्री की सेवा करना।"),
        ["VisitorInformation"] = ("Visitor Information", "મુલાકાતી માહિતી", "आगंतुक जानकारी"),
        ["AboutTirthSample"] = ("Sample content — Chuli Tirth is a place of Jain pilgrimage. This section should be updated by the administrator with verified history and significance.", "નમૂના સામગ્રી — ચુલી તીર્થ એ જૈન યાત્રાધામ છે. આ વિભાગ એડમિનિસ્ટ્રેટર દ્વારા ચકાસાયેલ ઇતિહાસ અને મહત્વ સાથે અપડેટ કરવો જોઈએ.", "नमूना सामग्री — चुली तीर्थ एक जैन तीर्थस्थल है। इस अनुभाग को प्रशासक द्वारा सत्यापित इतिहास और महत्व के साथ अपडेट किया जाना चाहिए।"),
        ["PleaseReviewRulesPrefix"] = ("Please review our", "કૃપા કરીને અમારા", "कृपया हमारे"),
        ["PleaseReviewRulesSuffix"] = ("before your visit.", "તમારી મુલાકાત પહેલાં જુઓ.", "अपनी यात्रा से पहले देखें।"),
        ["PleaseReviewRulesSuffixBooking"] = ("before confirming your stay.", "તમારું રોકાણ કન્ફર્મ કરતા પહેલાં જુઓ.", "अपना प्रवास पुष्ट करने से पहले देखें।"),

        // Bhojanshala / How to Reach
        ["BhojanshalaTimingNote"] = ("Timings may vary according to Tithi, season, sunrise/sunset, or management decisions.", "સમય તિથિ, ઋતુ, સૂર્યોદય/સૂર્યાસ્ત અથવા સંચાલન નિર્ણયો અનુસાર બદલાઈ શકે છે.", "समय तिथि, मौसम, सूर्योदय/सूर्यास्त या प्रबंधन निर्णयों के अनुसार बदल सकता है।"),
        ["ByRail"] = ("By Rail", "ટ્રેન દ્વારા", "ट्रेन द्वारा"),
        ["ByRailSample"] = ("Sample content — nearest railway station details to be updated by admin.", "નમૂના સામગ્રી — નજીકના રેલ્વે સ્ટેશનની વિગતો એડમિન દ્વારા અપડેટ કરવામાં આવશે.", "नमूना सामग्री — निकटतम रेलवे स्टेशन का विवरण एडमिन द्वारा अपडेट किया जाएगा।"),
        ["ByAir"] = ("By Air", "વિમાન દ્વારા", "हवाई मार्ग से"),
        ["ByAirSample"] = ("Sample content — nearest airport details to be updated by admin.", "નમૂના સામગ્રી — નજીકના એરપોર્ટની વિગતો એડમિન દ્વારા અપડેટ કરવામાં આવશે.", "नमूना सामग्री — निकटतम हवाई अड्डे का विवरण एडमिन द्वारा अपडेट किया जाएगा।"),
        ["ByRoad"] = ("By Road", "રોડ દ્વારા", "सड़क मार्ग से"),
        ["ByRoadSample"] = ("Sample content — bus station and driving directions to be updated by admin.", "નમૂના સામગ્રી — બસ સ્ટેશન અને ડ્રાઇવિંગ દિશાઓ એડમિન દ્વારા અપડેટ કરવામાં આવશે.", "नमूना सामग्री — बस स्टेशन और ड्राइविंग दिशाएं एडमिन द्वारा अपडेट की जाएंगी।"),
        ["ParkingAvailableDesc"] = ("On-site parking available for cars and buses.", "કાર અને બસ માટે સ્થળ પર પાર્કિંગ ઉપલબ્ધ છે.", "कार और बस के लिए परिसर में पार्किंग उपलब्ध है।"),

        // Booking flow
        ["NoRoomsAvailableMsg"] = ("No rooms are available for the selected dates and guest count. Please try different dates.", "પસંદ કરેલ તારીખો અને મહેમાન સંખ્યા માટે કોઈ રૂમ ઉપલબ્ધ નથી. કૃપા કરીને અલગ તારીખો અજમાવો.", "चयनित तिथियों और अतिथि संख्या के लिए कोई कमरा उपलब्ध नहीं है। कृपया अलग तिथियां आज़माएं।"),
        ["GuestsParen"] = ("guest(s)", "મહેમાન(ઓ)", "मेहमान(गण)"),
        ["RoomsParen"] = ("room(s)", "રૂમ(ો)", "कमरा/कमरे"),
        ["NightsParen"] = ("night(s)", "રાત(ો)", "रात/रातें"),
        ["AdultsParen"] = ("adult(s)", "પુખ્ત(ો)", "वयस्क"),
        ["ChildrenParen"] = ("child(ren)", "બાળક(બાળકો)", "बच्चा/बच्चे"),
        ["UpTo"] = ("Up to", "વધુમાં વધુ", "अधिकतम"),
        ["GuestsLower"] = ("guests", "મહેમાનો", "मेहमान"),
        ["BedsLower"] = ("beds", "પથારી", "बिस्तर"),
        ["Of"] = ("of", "માંથી", "में से"),
        ["RoomsAvailableLabel"] = ("rooms available", "રૂમ ઉપલબ્ધ", "कमरे उपलब्ध"),
        ["PerNight"] = ("/ night", "/ રાત", "/ रात"),
        ["ViewDetails"] = ("View Details", "વિગતો જુઓ", "विवरण देखें"),
        ["HotWaterLabel"] = ("Hot Water", "ગરમ પાણી", "गर्म पानी"),
        ["WifiLabel"] = ("Wi-Fi", "વાઇ-ફાઇ", "वाई-फाई"),
        ["ParkingLabel"] = ("Parking", "પાર્કિંગ", "पार्किंग"),
        ["AcPillLabel"] = ("AC", "એસી", "एसी"),
        ["RoomsIndexSubtitle"] = ("Choose AC or Non-AC — both in the same comfortable rooms.", "એસી અથવા નોન-એસી પસંદ કરો — બંને સમાન આરામદાયક રૂમમાં.", "एसी या नॉन-एसी चुनें — दोनों एक जैसे आरामदायक कमरों में।"),
        ["NoBookingFoundMsg"] = ("No booking found with that number.", "તે નંબર સાથે કોઈ બુકિંગ મળ્યું નથી.", "उस नंबर से कोई बुकिंग नहीं मिली।"),
        ["AtLeast"] = ("At least", "ઓછામાં ઓછું", "कम से कम"),
        ["OnePerRoomBooked"] = ("(one per room booked)", "(બુક કરેલ દરેક રૂમ માટે એક)", "(प्रत्येक बुक किए गए कमरे के लिए एक)"),
        ["AdultsMustBeAtLeastRooms"] = ("Adults must be at least the number of rooms.", "પુખ્તોની સંખ્યા ઓછામાં ઓછી રૂમની સંખ્યા જેટલી હોવી જોઈએ.", "वयस्कों की संख्या कमरों की संख्या से कम नहीं होनी चाहिए।"),
        ["BookingReservedFor15Min"] = ("is reserved for 15 minutes pending payment.", "ચુકવણી બાકી હોવાથી 15 મિનિટ માટે આરક્ષિત છે.", "भुगतान लंबित होने तक 15 मिनट के लिए आरक्षित है।"),
        ["Pay"] = ("Pay", "ચૂકવો", "भुगतान करें"),
        ["NowLabel"] = ("Now", "હમણાં", "अभी"),
        ["PaymentSecureNote"] = ("You'll be asked for UPI, card or netbanking details in a secure Razorpay window. Nothing is charged until you complete that step.", "તમને સુરક્ષિત Razorpay વિન્ડોમાં UPI, કાર્ડ અથવા નેટબેંકિંગ વિગતો માટે પૂછવામાં આવશે. તે પગલું પૂર્ણ ન થાય ત્યાં સુધી કંઈપણ ચાર્જ કરવામાં આવશે નહીં.", "आपसे सुरक्षित Razorpay विंडो में UPI, कार्ड या नेटबैंकिंग विवरण मांगा जाएगा। जब तक वह चरण पूरा नहीं होता, तब तक कुछ भी शुल्क नहीं लिया जाएगा।"),
        ["NoBookingsYet"] = ("You have no bookings yet.", "તમારી પાસે હજુ કોઈ બુકિંગ નથી.", "आपकी अभी तक कोई बुकिंग नहीं है।"),
        ["BrowseRooms"] = ("Browse rooms", "રૂમ બ્રાઉઝ કરો", "कमरे ब्राउज़ करें"),
        ["ToGetStarted"] = ("to get started.", "શરૂ કરવા માટે.", "शुरू करने के लिए।"),
        ["AmountLabel"] = ("Amount", "રકમ", "राशि"),
        ["VerifyingPayment"] = ("Verifying payment…", "ચુકવણી ચકાસી રહ્યા છીએ…", "भुगतान सत्यापित किया जा रहा है…"),
        ["PaymentNotVerifiedMsg"] = ("Payment could not be verified. If an amount was deducted, it will be refunded automatically — please contact us with your booking number.", "ચુકવણી ચકાસી શકાઈ નથી. જો રકમ કપાઈ ગઈ હોય, તો તે આપોઆપ રિફંડ કરવામાં આવશે — કૃપા કરીને તમારા બુકિંગ નંબર સાથે અમારો સંપર્ક કરો.", "भुगतान सत्यापित नहीं हो सका। यदि राशि कट गई है, तो वह स्वतः रिफंड हो जाएगी — कृपया अपने बुकिंग नंबर के साथ हमसे संपर्क करें।"),
        ["CouldNotReachServerMsg"] = ("Could not reach the server to confirm payment. Please check your connection and try again.", "ચુકવણીની પુષ્ટિ કરવા માટે સર્વર સુધી પહોંચી શકાયું નથી. કૃપા કરીને તમારું કનેક્શન તપાસો અને ફરી પ્રયાસ કરો.", "भुगतान की पुष्टि के लिए सर्वर तक नहीं पहुंचा जा सका। कृपया अपना कनेक्शन जांचें और पुनः प्रयास करें।"),
        ["PaymentWindowClosedMsg"] = ("Payment window closed before completing. Click Pay Now to try again.", "ચુકવણી વિન્ડો પૂર્ણ થયા પહેલાં બંધ થઈ ગઈ. ફરી પ્રયાસ કરવા માટે 'હમણાં ચૂકવો' પર ક્લિક કરો.", "भुगतान विंडो पूरा होने से पहले बंद हो गई। पुनः प्रयास करने के लिए 'अभी भुगतान करें' पर क्लिक करें।"),
        ["PaymentFailedPrefix"] = ("Payment failed:", "ચુકવણી નિષ્ફળ:", "भुगतान विफल:"),

        // Form field labels (used in place of asp-for auto-labels, which aren't localized)
        ["FirstNameLabel"] = ("First Name", "પ્રથમ નામ", "पहला नाम"),
        ["LastNameLabel"] = ("Last Name", "અટક", "अंतिम नाम"),
        ["MobileNumberLabel"] = ("Mobile Number", "મોબાઇલ નંબર", "मोबाइल नंबर"),
        ["EmailLabel"] = ("Email", "ઇમેઇલ", "ईमेल"),
        ["AddressLabel"] = ("Address", "સરનામું", "पता"),
        ["CityLabel"] = ("City", "શહેર", "शहर"),
        ["StateLabel"] = ("State", "રાજ્ય", "राज्य"),
        ["CountryLabel"] = ("Country", "દેશ", "देश"),
        ["ChildrenLabel"] = ("Children", "બાળકો", "बच्चे"),
        ["SpecialRequirementsLabel"] = ("Special Requirements", "ખાસ જરૂરિયાતો", "विशेष आवश्यकताएं"),
        ["NameLabel"] = ("Name", "નામ", "नाम"),
        ["SubjectLabel"] = ("Subject", "વિષય", "विषय"),
        ["MessageLabel"] = ("Message", "સંદેશ", "संदेश"),

        // BookingRule categories (DB field has no Gu/Hi column, so these are looked up by the
        // raw category string — T() falls back to the English key if it's ever a category not
        // listed here, e.g. one added later via Admin)
        ["Timing"] = ("Timing", "સમય", "समय"),
        ["Eligibility"] = ("Eligibility", "પાત્રતા", "पात्रता"),
        ["Conduct"] = ("Conduct", "આચરણ", "आचरण"),
        ["Cancellation"] = ("Cancellation", "રદ્દીકરણ", "रद्दीकरण"),
        ["Occupancy"] = ("Occupancy", "ક્ષમતા", "क्षमता"),

        ["AgreeToPrefix"] = ("I agree to the", "હું", "मैं"),
        ["DharamshalaRulesLink"] = ("Dharamshala rules", "ધર્મશાળાના નિયમો", "धर्मशाला के नियमों"),
        ["AgreeToAnd"] = ("and", "અને", "और"),
        ["TermsAndConditionsLink"] = ("Terms & Conditions", "નિયમો અને શરતો", "नियम और शर्तों"),
        ["AgreeToSuffix"] = ("(including the cancellation/refund policy).", "(રદ્દીકરણ/રિફંડ નીતિ સહિત) સાથે સંમત છું.", "(रद्दीकरण/रिफंड नीति सहित) से सहमत हूं।"),
        ["SampleContentFooterNote"] = ("(Sample content — configurable in Admin)", "(નમૂના સામગ્રી — એડમિનમાં ગોઠવી શકાય તેવી)", "(नमूना सामग्री — एडमिन में कॉन्फ़िगर करने योग्य)"),

        // Account pages
        ["ForgotPasswordHeading"] = ("Forgot Password", "પાસવર્ડ ભૂલી ગયા", "पासवर्ड भूल गए"),
        ["ForgotPasswordDesc"] = ("Enter your account email and we'll send you a link to reset your password.", "તમારો એકાઉન્ટ ઇમેઇલ દાખલ કરો અને અમે તમને પાસવર્ડ રીસેટ કરવાની લિંક મોકલીશું.", "अपना खाता ईमेल दर्ज करें और हम आपको पासवर्ड रीसेट करने का लिंक भेजेंगे।"),
        ["ForgotPasswordLink"] = ("Forgot password?", "પાસવર્ડ ભૂલી ગયા?", "पासवर्ड भूल गए?"),
        ["SendResetLink"] = ("Send Reset Link", "રીસેટ લિંક મોકલો", "रीसेट लिंक भेजें"),
        ["BackToLogin"] = ("Back to login", "લોગિન પર પાછા જાઓ", "लॉगिन पर वापस जाएं"),
        ["ResetPasswordHeading"] = ("Reset Password", "પાસવર્ડ રીસેટ કરો", "पासवर्ड रीसेट करें"),
        ["NewPasswordLabel"] = ("New Password", "નવો પાસવર્ડ", "नया पासवर्ड"),
        ["ConfirmPasswordLabel"] = ("Confirm Password", "પાસવર્ડની પુષ્ટિ કરો", "पासवर्ड की पुष्टि करें"),
        ["PasswordLabel"] = ("Password", "પાસવર્ડ", "पासवर्ड"),
        ["EmailOrMobileLabel"] = ("Email or Mobile", "ઇમેઇલ અથવા મોબાઇલ", "ईमेल या मोबाइल"),
        ["RememberMeLabel"] = ("Remember me", "મને યાદ રાખો", "मुझे याद रखें"),
        ["NewHerePrefix"] = ("New here?", "નવા છો?", "नए हैं?"),
        ["CreateAnAccountLink"] = ("Create an account", "ખાતું બનાવો", "खाता बनाएं"),
        ["CheckYourEmailTitle"] = ("Check Your Email", "તમારો ઇમેઇલ તપાસો", "अपना ईमेल जांचें"),
        ["ResetLinkSentMsg"] = ("If an account exists with that email, a password reset link has been sent. It will expire in 1 hour.", "જો તે ઇમેઇલ સાથે એકાઉન્ટ અસ્તિત્વમાં છે, તો પાસવર્ડ રીસેટ લિંક મોકલવામાં આવી છે. તે 1 કલાકમાં સમાપ્ત થશે.", "यदि उस ईमेल से कोई खाता मौजूद है, तो पासवर्ड रीसेट लिंक भेज दिया गया है। यह 1 घंटे में समाप्त हो जाएगा।"),
        ["FullNameLabel"] = ("Full Name", "પૂરું નામ", "पूरा नाम"),

        // Error pages
        ["AccessForbiddenHeading"] = ("Access Forbidden", "પ્રવેશ પ્રતિબંધિત", "पहुंच वर्जित"),
        ["SomethingWentWrongHeading"] = ("Something Went Wrong", "કંઈક ખોટું થયું", "कुछ गलत हो गया"),
        ["UnexpectedErrorMsg"] = ("An unexpected error occurred. Our team has been notified. Please try again shortly.", "એક અણધારી ભૂલ આવી. અમારી ટીમને જાણ કરવામાં આવી છે. કૃપા કરીને થોડી વાર પછી ફરી પ્રયાસ કરો.", "एक अप्रत्याशित त्रुटि हुई। हमारी टीम को सूचित कर दिया गया है। कृपया थोड़ी देर बाद पुनः प्रयास करें।"),
        ["PageNotFoundHeading"] = ("Page Not Found", "પૃષ્ઠ મળ્યું નથી", "पेज नहीं मिला"),
        ["PageNotFoundMsg"] = ("The page you are looking for does not exist or may have been moved.", "તમે શોધી રહ્યાં છો તે પૃષ્ઠ અસ્તિત્વમાં નથી અથવા ખસેડવામાં આવ્યું હોઈ શકે છે.", "आप जिस पेज की तलाश कर रहे हैं वह मौजूद नहीं है या स्थानांतरित किया गया हो सकता है।"),
        ["SkipToMainContent"] = ("Skip to main content", "મુખ્ય સામગ્રી પર જાઓ", "मुख्य सामग्री पर जाएं"),
    };

    public static string T(CultureInfo culture, string key)
    {
        if (!Map.TryGetValue(key, out var v)) return key;
        return culture.TwoLetterISOLanguageName switch
        {
            "gu" => v.Gu,
            "hi" => v.Hi,
            _ => v.En
        };
    }
}
